version: '3.8'

services:
  remote-command-server:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
